event_inherited();
damage = 4;
durability = 5;
crit = 10;
item = "Knife";
index = 0;
state = "NONE";
xspeed = irandom_range(-6,6);
yspeed = irandom_range(-6, -3);
icon = s_knife_i;
obj = self;
wid = 10;
create_shadow("small", self, y, z);
type = "Short";
flavor_txt = "Short And Effective";
distance = 64;