event_inherited();
damage = 1;
durability = 3;
item = "Extra Action";
index = 0;
state = "NONE";
xspeed = irandom_range(-6,6);
yspeed = irandom_range(-6, -3);
icon = s_extra_action_i;
spr = s_extra_action;
obj = self;
create_shadow("small", self, y, z);
wid = 16;
flavor_txt = "A Potion Of Extra Actions. Grants A Second Action Per Turn To Unleash Devastating Offensive Power. Can Be Used 3 Times";