damage = 5;
durability = 15;
crit = 20;
item = "King Sword";
index = 0;
state = "NONE";
xspeed = irandom_range(-6,6);
yspeed = irandom_range(-6, -3);
icon = s_king_sword_i;
width = 25;
create_shadow("large", self, y, z);
type = "Long";