event_inherited();
damage = 15;
durability = 1;
item = "Coins";
index = 0;
state = "Idle";
//xspeed = irandom_range(-6,6);
//yspeed = irandom_range(-6, -3);
icon = s_coin;
spr = s_coins;
obj = self;
create_shadow("small", self, y, z);
wid = 8;
flavor_txt = "Money :)";